2023-10-24 14:30:02,536 - INFO - Creating cyngular service principal
2023-10-24 14:30:16,769 - INFO - Creating CyngularRG resource group
2023-10-24 14:30:19,921 - INFO - Creating audit storage account
2023-10-24 14:30:44,155 - INFO - Creating nsg storage account
2023-10-24 14:31:14,233 - INFO - Getting the storage accounts connection strings
2023-10-24 14:31:18,522 - INFO - Listing client subscription ids
2023-10-24 14:31:19,306 - INFO - The current subscription is: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 14:31:39,066 - INFO - Exporting activity logs from subscription: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 14:32:22,788 - INFO - Creating CyngularNetWatcherRG resource group in subscription - b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 14:32:24,770 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-westeurope
2023-10-24 14:32:24,771 - INFO - Collecting nsg flow logs from resource group: azure-sentinel
2023-10-24 14:32:24,772 - INFO - Collecting nsg flow logs from resource group: mark-1-rg
2023-10-24 14:32:24,775 - INFO - Collecting nsg flow logs from resource group: CyngularRG
2023-10-24 14:32:24,775 - INFO - Collecting nsg flow logs from resource group: CyngularNetWatcherRG
2023-10-24 14:32:24,779 - INFO - Collecting nsg flow logs from resource group: clientx-resource-group
2023-10-24 14:32:24,781 - INFO - Collecting nsg flow logs from resource group: NetworkWatcherRG
2023-10-24 14:32:24,781 - INFO - Collecting nsg flow logs from resource group: sentinel
2023-10-24 14:32:24,781 - INFO - Collecting nsg flow logs from resource group: DeleteToday
2023-10-24 14:32:24,782 - INFO - Collecting nsg flow logs from resource group: linuxservicelab2250306406000
2023-10-24 14:32:32,685 - INFO - Collecting nsg flow logs from resource group: MC_DeleteToday_tal-k-test_westus
2023-10-24 14:32:35,107 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-northeurope
2023-10-24 14:33:10,987 - INFO - Importing diagnostic settings
2023-10-24 14:33:14,816 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-24 14:33:14,816 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-24 14:33:14,817 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 59, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 190, in export_diagnostic_settings
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 53, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-24 14:33:14,817 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 59, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 190, in export_diagnostic_settings
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 53, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-24 14:33:16,545 - INFO - FINISHED ONBOARDING
2023-10-24 14:33:16,547 - INFO - Importing public key
2023-10-24 14:33:16,661 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600000c548d0.Dvirs-MacBook-Air.local.64704': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"

2023-10-24 14:33:16,662 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600000c548d0.Dvirs-MacBook-Air.local.64704': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 59, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 76, in import_public_key
    return cli(args)
           ^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 53, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600000c548d0.Dvirs-MacBook-Air.local.64704': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"


2023-10-24 14:33:16,662 - INFO - Encrypting .local/jokers_data.txt file with public key
2023-10-24 14:33:16,687 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000011f46c0.Dvirs-MacBook-Air.local.64706': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000011f4780.Dvirs-MacBook-Air.local.64706': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"

2023-10-24 14:33:16,688 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000011f46c0.Dvirs-MacBook-Air.local.64706': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000011f4780.Dvirs-MacBook-Air.local.64706': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 59, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 88, in encrypt_data
    return cli(args)
           ^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 53, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 38, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000011f46c0.Dvirs-MacBook-Air.local.64706': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000011f4780.Dvirs-MacBook-Air.local.64706': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"


2023-10-24 15:50:27,168 - INFO -  STARTING CYNGULAR ONBOARING PROCESS
2023-10-24 15:50:33,776 - INFO - Adding extension named account
2023-10-24 15:50:47,778 - INFO - Creating cyngular service principal
2023-10-24 15:51:02,404 - INFO - Creating CyngularRG resource group
2023-10-24 15:51:05,121 - INFO - Creating audit storage account
2023-10-24 15:51:29,340 - INFO - Creating nsg storage account
2023-10-24 15:52:00,362 - INFO - Getting the storage accounts connection strings
2023-10-24 15:52:04,006 - INFO - Listing client subscription ids
2023-10-24 15:52:04,957 - INFO - The current subscription is: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 15:52:10,721 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Pool Operator\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Disk Pool Operator --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

2023-10-24 15:52:10,721 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Pool Operator\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Disk Pool Operator --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 130, in assign_subscription_role
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Pool Operator\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Disk Pool Operator --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"


2023-10-24 15:52:11,503 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Operator for Managed Disks\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Data Operator for Managed Disks --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

2023-10-24 15:52:11,504 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Operator for Managed Disks\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Data Operator for Managed Disks --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 130, in assign_subscription_role
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Operator for Managed Disks\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Data Operator for Managed Disks --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"


2023-10-24 15:52:12,291 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Snapshot Contributor\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Disk Snapshot Contributor --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

2023-10-24 15:52:12,291 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Snapshot Contributor\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Disk Snapshot Contributor --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 130, in assign_subscription_role
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Snapshot Contributor\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Disk Snapshot Contributor --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"


2023-10-24 15:52:13,082 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Sentinel Reader\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Microsoft Sentinel Reader --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

2023-10-24 15:52:13,083 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Sentinel Reader\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Microsoft Sentinel Reader --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 130, in assign_subscription_role
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b'ERROR: unrecognized arguments: Sentinel Reader\n\nExamples from AI knowledge base:\naz role assignment create --assignee sp_name --role a_role\nCreate role assignment for an assignee.\n\naz role assignment create --assignee 00000000-0000-0000-0000-000000000000 --role "Storage Account Key Operator Service Role" --scope $id\nCreate a new role assignment for a user, group, or service principal. (autogenerated)\n\nhttps://docs.microsoft.com/en-US/cli/azure/role/assignment#az_role_assignment_create\nRead more about the command in reference docs\n'  " in => assign_subscription_role
az role assignment create --assignee-object-id f694d121-987e-4e45-afd6-630525495986 --assignee-principal-type ServicePrincipal --role Microsoft Sentinel Reader --scope /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba"


2023-10-24 15:52:13,083 - INFO - Exporting activity logs from subscription: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 15:52:57,281 - INFO - Creating CyngularNetWatcherRG resource group in subscription - b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 15:53:00,339 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-westeurope
2023-10-24 15:53:00,340 - INFO - Collecting nsg flow logs from resource group: azure-sentinel
2023-10-24 15:53:00,341 - INFO - Collecting nsg flow logs from resource group: mark-1-rg
2023-10-24 15:53:00,343 - INFO - Collecting nsg flow logs from resource group: CyngularRG
2023-10-24 15:53:00,344 - INFO - Collecting nsg flow logs from resource group: CyngularNetWatcherRG
2023-10-24 15:53:00,347 - INFO - Collecting nsg flow logs from resource group: clientx-resource-group
2023-10-24 15:53:00,348 - INFO - Collecting nsg flow logs from resource group: NetworkWatcherRG
2023-10-24 15:53:00,350 - INFO - Collecting nsg flow logs from resource group: sentinel
2023-10-24 15:53:00,351 - INFO - Collecting nsg flow logs from resource group: DeleteToday
2023-10-24 15:53:00,355 - INFO - Collecting nsg flow logs from resource group: linuxservicelab2250306406000
2023-10-24 15:53:09,032 - INFO - Collecting nsg flow logs from resource group: MC_DeleteToday_tal-k-test_westus
2023-10-24 15:53:10,269 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-northeurope
2023-10-24 15:53:37,795 - INFO - Importing diagnostic settings
2023-10-24 15:53:41,248 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-24 15:53:41,249 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-24 15:53:41,249 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 195, in export_diagnostic_settings
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-24 15:53:41,249 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 195, in export_diagnostic_settings
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-24 15:53:42,830 - INFO - FINISHED ONBOARDING
2023-10-24 15:53:42,832 - INFO - Importing public key
2023-10-24 15:53:42,923 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000007609f0.Dvirs-MacBook-Air.local.69457': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"

2023-10-24 15:53:42,923 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000007609f0.Dvirs-MacBook-Air.local.69457': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 81, in import_public_key
    return cli(args)
           ^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000007609f0.Dvirs-MacBook-Air.local.69457': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"


2023-10-24 15:53:42,923 - INFO - Encrypting .local/jokers_data.txt file with public key
2023-10-24 15:53:42,936 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000023a0ab0.Dvirs-MacBook-Air.local.69459': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000023a09f0.Dvirs-MacBook-Air.local.69459': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"

2023-10-24 15:53:42,937 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000023a0ab0.Dvirs-MacBook-Air.local.69459': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000023a09f0.Dvirs-MacBook-Air.local.69459': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 93, in encrypt_data
    return cli(args)
           ^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000023a0ab0.Dvirs-MacBook-Air.local.69459': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000023a09f0.Dvirs-MacBook-Air.local.69459': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"


2023-10-24 15:57:51,498 - INFO -  STARTING CYNGULAR ONBOARING PROCESS
2023-10-24 15:57:57,120 - INFO - Adding extension named account
2023-10-24 15:58:12,843 - INFO - Creating cyngular service principal
2023-10-24 15:58:13,307 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: Please run 'az login' to setup account.\n"  " in => create_cyngular_service_principal
az ad sp create-for-rbac --name CyngularSP"

2023-10-24 15:58:13,307 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: Please run 'az login' to setup account.\n"  " in => create_cyngular_service_principal
az ad sp create-for-rbac --name CyngularSP"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 109, in create_cyngular_service_principal
    res = cli(args)
          ^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: Please run 'az login' to setup account.\n"  " in => create_cyngular_service_principal
az ad sp create-for-rbac --name CyngularSP"


2023-10-24 15:58:13,307 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 332, in main
    (
TypeError: cannot unpack non-iterable NoneType object

2023-10-24 16:00:44,935 - INFO -  STARTING CYNGULAR ONBOARING PROCESS
2023-10-24 16:00:52,890 - INFO - Adding extension named account
2023-10-24 16:01:06,175 - INFO - Creating cyngular service principal
2023-10-24 16:01:21,866 - INFO - Creating CyngularRG resource group
2023-10-24 16:01:24,385 - INFO - Creating audit storage account
2023-10-24 16:01:54,039 - INFO - Creating nsg storage account
2023-10-24 16:02:17,013 - INFO - Getting the storage accounts connection strings
2023-10-24 16:02:20,728 - INFO - Listing client subscription ids
2023-10-24 16:02:21,508 - INFO - The current subscription is: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 16:02:41,552 - INFO - Exporting activity logs from subscription: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 16:03:37,197 - INFO - Creating CyngularNetWatcherRG resource group in subscription - b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-24 16:03:39,477 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-westeurope
2023-10-24 16:03:39,477 - INFO - Collecting nsg flow logs from resource group: azure-sentinel
2023-10-24 16:03:39,479 - INFO - Collecting nsg flow logs from resource group: mark-1-rg
2023-10-24 16:03:39,479 - INFO - Collecting nsg flow logs from resource group: CyngularRG
2023-10-24 16:03:39,481 - INFO - Collecting nsg flow logs from resource group: CyngularNetWatcherRG
2023-10-24 16:03:39,481 - INFO - Collecting nsg flow logs from resource group: clientx-resource-group
2023-10-24 16:03:39,481 - INFO - Collecting nsg flow logs from resource group: NetworkWatcherRG
2023-10-24 16:03:39,483 - INFO - Collecting nsg flow logs from resource group: sentinel
2023-10-24 16:03:39,486 - INFO - Collecting nsg flow logs from resource group: DeleteToday
2023-10-24 16:03:39,493 - INFO - Collecting nsg flow logs from resource group: linuxservicelab2250306406000
2023-10-24 16:03:48,998 - INFO - Collecting nsg flow logs from resource group: MC_DeleteToday_tal-k-test_westus
2023-10-24 16:03:49,656 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-northeurope
2023-10-24 16:04:20,742 - INFO - Importing diagnostic settings
2023-10-24 16:04:24,102 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-24 16:04:24,102 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 195, in export_diagnostic_settings
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-24 16:04:24,134 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-24 16:04:24,134 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 64, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 195, in export_diagnostic_settings
    cli(args)
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
    raise Exception(error_msg)
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
    raise ValueError(str(err) + '  "' + ' in => ' + sys._getframe(1).f_code.co_name + "\n" + " ".join(args) + '"')
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-24 16:04:25,776 - INFO - FINISHED ONBOARDING
2023-10-24 16:04:25,778 - INFO - Importing public key
2023-10-24 16:04:26,614 - INFO - Encrypting .local/jokers_data.txt file with public key
2023-10-24 16:36:32,779 - INFO -  STARTING CYNGULAR ONBOARING PROCESS
2023-10-25 00:16:24,454 - INFO -  STARTING CYNGULAR ONBOARING PROCESS
2023-10-25 00:16:31,980 - INFO - Adding extension named account
2023-10-25 00:16:39,359 - INFO - Creating cyngular service principal
2023-10-25 00:17:01,037 - INFO - Creating CyngularRG resource group
2023-10-25 00:17:03,915 - INFO - Creating audit storage account
2023-10-25 00:17:35,389 - INFO - Creating nsg storage account
2023-10-25 00:18:05,124 - INFO - Getting the storage accounts connection strings
2023-10-25 00:18:11,109 - INFO - Listing client subscription ids
2023-10-25 00:18:12,001 - INFO - The current subscription is: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-25 00:18:37,494 - INFO - Exporting activity logs from subscription: b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-25 00:19:21,107 - INFO - Creating CyngularNetWatcherRG resource group in subscription - b6c14413-fb13-4063-acd5-d47e2537a7ba
2023-10-25 00:19:24,133 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-westeurope
2023-10-25 00:19:24,133 - INFO - Collecting nsg flow logs from resource group: azure-sentinel
2023-10-25 00:19:24,135 - INFO - Collecting nsg flow logs from resource group: mark-1-rg
2023-10-25 00:19:24,136 - INFO - Collecting nsg flow logs from resource group: CyngularRG
2023-10-25 00:19:24,137 - INFO - Collecting nsg flow logs from resource group: CyngularNetWatcherRG
2023-10-25 00:19:24,139 - INFO - Collecting nsg flow logs from resource group: clientx-resource-group
2023-10-25 00:19:24,145 - INFO - Collecting nsg flow logs from resource group: NetworkWatcherRG
2023-10-25 00:19:24,148 - INFO - Collecting nsg flow logs from resource group: sentinel
2023-10-25 00:19:24,151 - INFO - Collecting nsg flow logs from resource group: DeleteToday
2023-10-25 00:19:24,151 - INFO - Collecting nsg flow logs from resource group: linuxservicelab2250306406000
2023-10-25 00:19:32,919 - INFO - Collecting nsg flow logs from resource group: MC_DeleteToday_tal-k-test_westus
2023-10-25 00:19:33,860 - INFO - Collecting nsg flow logs from resource group: cloud-shell-storage-northeurope
2023-10-25 00:20:04,915 - INFO - Importing diagnostic settings
2023-10-25 00:20:08,194 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-25 00:20:08,194 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

2023-10-25 00:20:08,195 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 63, in wrapper
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 195, in export_diagnostic_settings
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2 --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-25 00:20:08,195 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 63, in wrapper
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 195, in export_diagnostic_settings
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"ERROR: (ResourceTypeNotSupported) The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\nCode: ResourceTypeNotSupported\nMessage: The resource type 'microsoft.network/networkwatchers/flowlogs' does not support diagnostic settings.\n"  " in => export_diagnostic_settings
az monitor diagnostic-settings create --name CyngularDiagnostic --resource /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/flowLogs/cyngular --storage-account /subscriptions/b6c14413-fb13-4063-acd5-d47e2537a7ba/resourceGroups/CyngularRG/providers/Microsoft.Storage/storageAccounts/cyngularauditjokers --logs [{category:AuditEvent,enabled:true,retention-policy:{enabled:false,days:30}}]"


2023-10-25 00:20:10,126 - INFO - FINISHED ONBOARDING
2023-10-25 00:20:10,127 - INFO - Importing public key
2023-10-25 00:20:10,212 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000016c8a20.Dvirs-MacBook-Air.local.8945': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"

2023-10-25 00:20:10,212 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000016c8a20.Dvirs-MacBook-Air.local.8945': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 63, in wrapper
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 80, in import_public_key
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x00006000016c8a20.Dvirs-MacBook-Air.local.8945': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: no writable keyring found: Not found\ngpg: error reading '.local/cyngularPublic.key': General error\ngpg: import from '.local/cyngularPublic.key' failed: General error\ngpg: Total number processed: 0\n"  " in => import_public_key
gpg --import .local/cyngularPublic.key"


2023-10-25 00:20:10,212 - INFO - Encrypting .local/jokers_data.txt file with public key
2023-10-25 00:20:10,225 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600001f74c30.Dvirs-MacBook-Air.local.8946': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600001f700f0.Dvirs-MacBook-Air.local.8946': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --trust-model always --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"

2023-10-25 00:20:10,225 - CRITICAL - Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600001f74c30.Dvirs-MacBook-Air.local.8946': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600001f700f0.Dvirs-MacBook-Air.local.8946': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --trust-model always --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 63, in wrapper
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 93, in encrypt_data
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 58, in cli
Exception: Traceback (most recent call last):
  File "/Users/dvirgross/projects/Infra/Azure/azure-client-onboarding/CyngularOnboardingV1.2.2.py", line 43, in cli
ValueError: b"gpg: WARNING: unsafe ownership on homedir '/Users/dvirgross/.gnupg'\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600001f74c30.Dvirs-MacBook-Air.local.8946': Permission denied\ngpg: keyblock resource '/Users/dvirgross/.gnupg/pubring.kbx': Permission denied\ngpg: failed to create temporary file '/Users/dvirgross/.gnupg/.#lk0x0000600001f700f0.Dvirs-MacBook-Air.local.8946': Permission denied\ngpg: can't connect to the dirmngr: Permission denied\ngpg: error retrieving 'cyngularsecurity@gmail.com' via WKD: No dirmngr\ngpg: cyngularsecurity@gmail.com: skipped: No dirmngr\ngpg: .local/jokers_data.txt: encryption failed: No dirmngr\n"  " in => encrypt_data
gpg --trust-model always --encrypt --armor -r cyngularsecurity@gmail.com .local/jokers_data.txt"


